<?php
namespace Yay_Currency\Helpers;

use Yay_Currency\Utils\SingletonTrait;
class TranslateHelper {

	use SingletonTrait;

	protected function __construct() {}

	public static function get_translations() {
		return array(
			// App
			'Manage Currency'                              => __( 'Manage Currency', 'yay-currency' ),
			'Checkout Options'                             => __( 'Checkout Options', 'yay-currency' ),
			'Display Options'                              => __( 'Display Options', 'yay-currency' ),
			'Advanced Settings'                            => __( 'Advanced Settings', 'yay-currency' ),
			'Save Changes'                                 => __( 'Save Changes', 'yay-currency' ),
			'Settings saved!'                              => __( 'Settings saved!', 'yay-currency' ),
			'Oops! Something went wrong!'                  => __( 'Oops! Something went wrong!', 'yay-currency' ),
			'Chat with support'                            => __( 'Chat with support', 'yay-currency' ),
			'Documentation'                                => __( 'Documentation', 'yay-currency' ),
			// Currency Settings
			'Change default store currency?'               => __( 'Change default store currency?', 'yay-currency' ),
			'This will update your WooCommerce base currency from' => __( 'This will update your WooCommerce base currency from', 'yay-currency' ),
			'to selected currency.'                        => __( 'to selected currency.', 'yay-currency' ),
			'Default currency'                             => __( 'Default currency', 'yay-currency' ),
			'This is a store-wide setting that affects how product base prices are stored and displayed.' => __( 'This is a store-wide setting that affects how product base prices are stored and displayed.', 'yay-currency' ),
			// Manager Currency
			'Update all currencies\'s rate'                => __( 'Update all currencies\'s rate', 'yay-currency' ),
			'Your default currency is '                    => __( 'Your default currency is ', 'yay-currency' ),
			'Change'                                       => __( 'Change', 'yay-currency' ),
			'Add New Currency'                             => __( 'Add New Currency', 'yay-currency' ),
			'Currency'                                     => __( 'Currency', 'yay-currency' ),
			'currency'                                     => __( 'currency', 'yay-currency' ),
			'This controls what currency prices are listed at in the catalog and which currency gateways will take payments in.' => __( 'This controls what currency prices are listed at in the catalog and which currency gateways will take payments in.', 'yay-currency' ),
			'Preview'                                      => __( 'Preview', 'yay-currency' ),
			'This show sample amount'                      => __( 'This show sample amount', 'yay-currency' ),
			'Rate'                                         => __( 'Rate', 'yay-currency' ),
			'This sets the exchange rate of currency based on default currency' => __( 'This sets the exchange rate of currency based on default currency', 'yay-currency' ),
			'Fee'                                          => __( 'Fee', 'yay-currency' ),
			'This sets the extra money to compensate the difference of currency' => __( 'This sets the extra money to compensate the difference of currency', 'yay-currency' ),
			'Action'                                       => __( 'Action', 'yay-currency' ),
			'Auto'                                         => __( 'Auto', 'yay-currency' ),
			'Fixed'                                        => __( 'Fixed', 'yay-currency' ),
			'Update currency\'s rate'                      => __( 'Update currency\'s rate', 'yay-currency' ),
			'Config currency\'s format'                    => __( 'Config currency\'s format', 'yay-currency' ),
			'Delete currency'                              => __( 'Delete currency', 'yay-currency' ),
			'Are you sure you want to delete this currency?' => __( 'Are you sure you want to delete this currency?', 'yay-currency' ),
			'Successfully deleted!'                        => __( 'Successfully deleted!', 'yay-currency' ),
			'Failed to delete currency'                    => __( 'Failed to delete currency', 'yay-currency' ),
			'Exchange rate updated!'                       => __( 'Exchange rate updated!', 'yay-currency' ),
			'Unable to update exchange rate.'              => __( 'Unable to update exchange rate.', 'yay-currency' ),
			'Live exchange rate unavailable. Please update manually for this currency.' => __( 'Live exchange rate unavailable. Please update manually for this currency.', 'yay-currency' ),
			'Troubleshoot'                                 => __( 'Troubleshoot', 'yay-currency' ),

			'Exchange rate is required!'                   => __( 'Exchange rate is required!', 'yay-currency' ),
			'Fix it now'                                   => __( 'Fix it now', 'yay-currency' ),
			'Contact us'                                   => __( 'Contact us', 'yay-currency' ),
			'Configure'                                    => __( 'Configure', 'yay-currency' ),
			'Currency symbol position'                     => __( 'Currency symbol position', 'yay-currency' ),
			'Currency code position'                       => __( 'Currency code position', 'yay-currency' ),
			'Currency position'                            => __( 'Currency position', 'yay-currency' ),
			'Thousand separator'                           => __( 'Thousand separator', 'yay-currency' ),
			'Decimal separator'                            => __( 'Decimal separator', 'yay-currency' ),
			'Number of decimals'                           => __( 'Number of decimals', 'yay-currency' ),
			'Rounding'                                     => __( 'Rounding', 'yay-currency' ),
			'Custom rounding of converted prices'          => __( 'Custom rounding of converted prices', 'yay-currency' ),
			'To'                                           => __( 'To', 'yay-currency' ),
			'Round the converted price to achieve the target ending. Eg: 365.36 becomes 370 when rounding up to the nearest 10' => __( 'Round the converted price to achieve the target ending. Eg: 365.36 becomes 370 when rounding up to the nearest 10', 'yay-currency' ),
			'Minus'                                        => __( 'Minus', 'yay-currency' ),
			'Deduct this amount from the above rounded price. Eg: 370 becomes 369.99 after deducting 0.01' => __( 'Deduct this amount from the above rounded price. Eg: 370 becomes 369.99 after deducting 0.01', 'yay-currency' ),
			'Enter test amount'                            => __( 'Enter test amount', 'yay-currency' ),
			'Result'                                       => __( 'Result', 'yay-currency' ),
			'Left'                                         => __( 'Left', 'yay-currency' ),
			'Right'                                        => __( 'Right', 'yay-currency' ),
			'Left with space'                              => __( 'Left with space', 'yay-currency' ),
			'Right with space'                             => __( 'Right with space', 'yay-currency' ),
			'Not display'                                  => __( 'Not display', 'yay-currency' ),
			'Disabled'                                     => __( 'Disabled', 'yay-currency' ),
			'Up'                                           => __( 'Up', 'yay-currency' ),
			'Down'                                         => __( 'Down', 'yay-currency' ),
			'Nearest'                                      => __( 'Nearest', 'yay-currency' ),

			// Checkout Options
			'Checkout in different currency'               => __( 'Checkout in different currency', 'yay-currency' ),
			'This sets the ability to checkout in a variety of currencies' => __( 'This sets the ability to checkout in a variety of currencies', 'yay-currency' ),

			'Checkout in fallback currency'                => __( 'Checkout in fallback currency', 'yay-currency' ),
			'Type to search currency...'                   => __( 'Type to search currency...', 'yay-currency' ),
			'This currency is used as a fallback where the default currency can’t be displayed on checkout page.' => __( 'This currency is used as a fallback where the default currency can’t be displayed on checkout page.', 'yay-currency' ),
			'The fallback currency can not be disabled.'   => __( 'The fallback currency can not be disabled.', 'yay-currency' ),
			'Are you sure to disable the default currency at checkout?' => __( 'Are you sure to disable the default currency at checkout?', 'yay-currency' ),
			'You would need to select a fallback currency.' => __( 'You would need to select a fallback currency.', 'yay-currency' ),
			'Status'                                       => __( 'Status', 'yay-currency' ),
			'This sets the currency is applied in checkout' => __( 'This sets the currency is applied in checkout', 'yay-currency' ),
			'Payment Methods'                              => __( 'Payment Methods', 'yay-currency' ),
			'All payment methods'                          => __( 'All payment methods', 'yay-currency' ),
			'Search payment methods'                       => __( 'Search payment methods', 'yay-currency' ),
			'Force payment in a specific currency'         => __( 'Force payment in a specific currency', 'yay-currency' ),
			'This allows customers to place orders in different currencies but forces payment based on billing/shipping country at checkout.' => __( 'This allows customers to place orders in different currencies but forces payment based on billing/shipping country at checkout.', 'yay-currency' ),
			'Billing'                                      => __( 'Billing', 'yay-currency' ),
			'Shipping'                                     => __( 'Shipping', 'yay-currency' ),
			'Display force payment notice at checkout'     => __( 'Display force payment notice at checkout', 'yay-currency' ),
			'You can include these shortcodes'             => __( 'You can include these shortcodes', 'yay-currency' ),
			'Reload Checkout page'                         => __( 'Reload checkout page', 'yay-currency' ),
			'This sets the avoid cases of not matching currency with a few Paypal payment methods.' => __( 'This sets the avoid cases of not matching currency with a few Paypal payment methods.', 'yay-currency' ),
			'Force currency for a specific payment method' => __( 'Force currency for a specific payment method', 'yay-currency' ),
			'This allows customers to set a specific currency for a specific payment gateway on the checkout page.' => __( 'This allows customers to set a specific currency for a specific payment gateway on the checkout page.', 'yay-currency' ),
			'Default (Auto detect)'                        => __( 'Default (Auto detect)', 'yay-currency' ),
			'This payment method was disabled.'            => __( 'This payment method was disabled.', 'yay-currency' ),
			// Display Options
			'Switcher Location'                            => __( 'Switcher Location', 'yay-currency' ),
			'Choose where to display the currency switcher.' => __( 'Choose where to display the currency switcher.', 'yay-currency' ),
			'Show on Single Product Page'                  => __( 'Show on Single Product Page', 'yay-currency' ),
			'Before short description'                     => __( 'Before short description', 'yay-currency' ),
			'After short description'                      => __( 'After short description', 'yay-currency' ),
			'Shortcode'                                    => __( 'Shortcode', 'yay-currency' ),
			'Copy this shortcode to display currency switcher anywhere you want.' => __( 'Copy this shortcode to display currency switcher anywhere you want.', 'yay-currency' ),
			'Copied!'                                      => __( 'Copied!', 'yay-currency' ),
			'Click to copy'                                => __( 'Click to copy', 'yay-currency' ),
			'Switcher Customizer'                          => __( 'Switcher Customizer', 'yay-currency' ),
			'Customize the currency switcher used at the above positions.' => __( 'Customize the currency switcher used at the above positions.', 'yay-currency' ),
			'Show flag'                                    => __( 'Show flag', 'yay-currency' ),
			'Show currency name'                           => __( 'Show currency name', 'yay-currency' ),
			'Show currency symbol'                         => __( 'Show currency symbol', 'yay-currency' ),
			'Show currency code'                           => __( 'Show currency code', 'yay-currency' ),
			'Switcher size'                                => __( 'Switcher size', 'yay-currency' ),
			'Small'                                        => __( 'Small', 'yay-currency' ),
			'Medium'                                       => __( 'Medium', 'yay-currency' ),
			'Symbol'                                       => __( 'Symbol', 'yay-currency' ),
			'Code'                                         => __( 'Code', 'yay-currency' ),

			// Advance Settings

			'Fixed product price for each currency'        => __( 'Fixed product price for each currency', 'yay-currency' ),
			'By enabling this option, you can go to <b>Products</b> settings to set up fixed product prices based on currency.' => __( 'By enabling this option, you can go to <b>Products</b> settings to set up fixed product prices based on currency.', 'yay-currency' ),
			'Update exchange rate automatically'           => __( 'Update exchange rate automatically', 'yay-currency' ),
			'This sets the interval of update exchange rate automation.' => __( 'This sets the interval of update exchange rate automation.', 'yay-currency' ),
			'Minute(s)'                                    => __( 'Minute(s)', 'yay-currency' ),
			'Hour(s)'                                      => __( 'Hour(s)', 'yay-currency' ),
			'Day(s)'                                       => __( 'Day(s)', 'yay-currency' ),
			'Finance API'                                  => __( 'Finance API', 'yay-currency' ),
			'Default'                                      => __( 'Default', 'yay-currency' ),
			'Google Finance'                               => __( 'Google Finance', 'yay-currency' ),
			'Yahoo Finance'                                => __( 'Yahoo Finance', 'yay-currency' ),
			'Cuex'                                         => __( 'Cuex', 'yay-currency' ),
			'FawazCurrency'                                => __( 'FawazCurrency', 'yay-currency' ),
			'Xe'                                           => __( 'Xe', 'yay-currency' ),
			'Auto select currency by countries'            => __( 'Auto select currency by countries', 'yay-currency' ),
			'This sets the display currency depends on the customer\'s country.' => __( 'This sets the display currency depends on the customer\'s country.', 'yay-currency' ),
			'Countries'                                    => __( 'Countries', 'yay-currency' ),
			'Apply to Google Crawlers (or Bots)'           => __( 'Apply to Google Crawlers (or Bots)', 'yay-currency' ),
			'Enable this option to apply Auto Select Currency by Country to Google Crawlers (or Bots). If disabled, Google Crawlers (or Bots) will use your store’s default currency.' => __( 'Enable this option to apply Auto Select Currency by Country to Google Crawlers (or Bots). If disabled, Google Crawlers (or Bots) will use your store’s default currency.', 'yay-currency' ),
			'Display current currency notice on product page' => __( 'Display current currency notice on product page', 'yay-currency' ),

			'Show Approximate price'                       => __( 'Show Approximate price', 'yay-currency' ),
			'This displays approximate prices based on your country, e.g., United States ($), United Kingdom (£), France (€), India (₹), etc.' => __( 'This displays approximate prices based on your country, e.g., United States ($), United Kingdom (£), France (€), India (₹), etc.', 'yay-currency' ),
			'Label'                                        => __( 'Label', 'yay-currency' ),
			'Enter the text you want to display for the Approximate Price label.' => __( 'Enter the text you want to display for the Approximate Price label.', 'yay-currency' ),
			'You can include the shortcode'                => __( 'You can include the shortcode', 'yay-currency' ),
			'to show the formatted approximate price based on the customer\'s location.' => __( 'to show the formatted approximate price based on the customer\'s location.', 'yay-currency' ),
			'NOTE'                                         => __( 'NOTE', 'yay-currency' ),
			'The formatted approximate price will be automatically appended to the end of the string if the label does not contain the' => __( 'The formatted approximate price will be automatically appended to the end of the string if the label does not contain the', 'yay-currency' ),
			'shortcode'                                    => __( 'shortcode', 'yay-currency' ),
			'Display on'                                   => __( 'Display on', 'yay-currency' ),
			'All elements'                                 => __( 'All elements', 'yay-currency' ),
			'Select the elements you want to display for the Approximate price.' => __( 'Select the elements you want to display for the Approximate price.', 'yay-currency' ),
			'Position'                                     => __( 'Position', 'yay-currency' ),
			'Before original price'                        => __( 'Before original price', 'yay-currency' ),
			'After original price'                         => __( 'After original price', 'yay-currency' ),
			'Select the position where you want the Approximate price to be displayed relative to the original price.' => __( 'Select the position where you want the Approximate price to be displayed relative to the original price.', 'yay-currency' ),
			'Approximately'                                => __( 'Approximately', 'yay-currency' ),
			'Polylang Compatible'                          => __( 'Polylang Compatible', 'yay-currency' ),
			'WPML Compatible'                              => __( 'WPML Compatible', 'yay-currency' ),
			'Language'                                     => __( 'Language', 'yay-currency' ),
			'Compatible with cache plugins'                => __( 'Compatible with cache plugins', 'yay-currency' ),
			'Enable this if you’re using a cache plugin( WP Super cache, W3 total cache, NitroPack, WP rocket, LiteSpeed Cache,etc.)' => __( 'Enable this if you’re using a cache plugin( WP Super cache, W3 total cache, NitroPack, WP rocket, LiteSpeed Cache,etc.)', 'yay-currency' ),
			'Loading mask'                                 => __( 'Loading mask', 'yay-currency' ),
			'Add Loading layer when loading price/switcher/symbol via AJAX' => __( 'Add Loading layer when loading price/switcher/symbol via AJAX', 'yay-currency' ),
			'Learn more'                                   => __( 'Learn more', 'yay-currency' ),

			// Upgrade Pro
			'You have used '                               => __( 'You have used ', 'yay-currency' ),
			'free currency.'                               => __( 'free currency.', 'yay-currency' ),
			'Upgrade'                                      => __( 'Upgrade', 'yay-currency' ),
			'Disable Default Currency at Checkout'         => __( 'Disable Default Currency at Checkout', 'yay-currency' ),
			'PRO'                                          => __( 'PRO', 'yay-currency' ),
			'This feature only available in PRO version.'  => __( 'This feature only available in PRO version.', 'yay-currency' ),
			'Upgrade Image'                                => __( 'Upgrade Image', 'yay-currency' ),
			'Currencies Limit Reached'                     => __( 'Currencies Limit Reached', 'yay-currency' ),
			'YayCurrency Lite version supports up to 3 currencies' => __( 'YayCurrency Lite version supports up to 3 currencies', 'yay-currency' ),
			'Please upgrade to have unlimited currencies and other premium features!' => __( 'Please upgrade to have unlimited currencies and other premium features!', 'yay-currency' ),
			'Unlimited Currencies'                         => __( 'Unlimited Currencies', 'yay-currency' ),
			'Auto Update Exchange Rate'                    => __( 'Auto Update Exchange Rate', 'yay-currency' ),
			'Work with WPML, Polylang and 20+ WooCommerce Plugins' => __( 'Work with WPML, Polylang and 20+ WooCommerce Plugins', 'yay-currency' ),
			'Premium Technical Support'                    => __( 'Premium Technical Support', 'yay-currency' ),
			'One-Time Payment'                             => __( 'One-Time Payment', 'yay-currency' ),
			'30-Day Refund Guarantee'                      => __( '30-Day Refund Guarantee', 'yay-currency' ),
			'Upgrade to YayCurrency Pro now'               => __( 'Upgrade to YayCurrency Pro now', 'yay-currency' ),
			'Third-Party Compatibility'                    => __( 'Third-Party Compatibility', 'yay-currency' ),
			'Show the currency according to the selected language, regardless of country or geolocation.' => __( 'Show the currency according to the selected language, regardless of country or geolocation.', 'yay-currency' ),
			'Enable Recommendations'                       => __( 'Enable Recommendations', 'yay-currency' ),
			'Show contextual recommendations that can be helpful for your WooCommerce store.' => __( 'Show contextual recommendations that can be helpful for your WooCommerce store.', 'yay-currency' ),
			// Countries Options
			'Search countries'                             => __( 'Search countries', 'yay-currency' ),
			'more'                                         => __( 'more', 'yay-currency' ),
			'Show less'                                    => __( 'Show less', 'yay-currency' ),
		);
	}
}
